import type { ExploreResource } from "@/types/resource";

export const fallbackRetailers: ExploreResource[] = [
  {
    id: "r1",
    kind: "retailer",
    name: "BSTN",
    url: "https://www.bstn.com",
    origin: "Allemagne",
    category: "Streetwear & sneakers",
    desc: "Catalogue très complet — sneakers, streetwear et créateurs. Souvent le premier endroit où retrouver des drops européens.",
    tags: ["Sneakers", "Streetwear", "Créateurs", "EU"],
  },
  {
    id: "r2",
    kind: "retailer",
    name: "Size?",
    url: "https://www.size.co.uk",
    origin: "UK",
    category: "Sneakers & streetwear",
    desc: "Référence UK pour les sneakers et le streetwear. Bon mix entre grands noms et marques émergentes.",
    tags: ["Sneakers", "Streetwear", "UK"],
  },
  {
    id: "r3",
    kind: "retailer",
    name: "Asphaltgold",
    url: "https://www.asphaltgold.com",
    origin: "Allemagne",
    category: "Streetwear",
    desc: "Sélection pointue côté streetwear et lifestyle. Utile quand tu cherches une pièce vue sur les réseaux.",
    tags: ["Streetwear", "Lifestyle", "Sélection pointue"],
  },
  {
    id: "r4",
    kind: "retailer",
    name: "Citadium",
    url: "https://www.citadium.com",
    origin: "France",
    category: "Streetwear & lifestyle",
    desc: "Institution parisienne — large choix de marques streetwear, workwear et créateurs accessibles en France.",
    tags: ["Streetwear", "France", "Multi-marques"],
  },
  {
    id: "r5",
    kind: "retailer",
    name: "END.",
    url: "https://www.endclothing.com",
    origin: "UK",
    category: "Mode contemporaine",
    desc: "Curateur sérieux — streetwear haut de gamme, tailoring moderne et collaborations exclusives.",
    tags: ["Premium", "Streetwear", "Collaborations"],
  },
];

export const fallbackAccounts: ExploreResource[] = [
  {
    id: "a1",
    kind: "account",
    name: "Vetements Magazine",
    url: "https://www.instagram.com/vetementsmagazine",
    category: "Culture mode",
    contentType: "Média",
    desc: "Média indépendant — décryptage mode, interviews et coulisses de l'industrie.",
    tags: ["Média", "Culture", "Analyse"],
    social: { instagram: "https://www.instagram.com/vetementsmagazine" },
  },
  {
    id: "a2",
    kind: "account",
    name: "Camino TV",
    url: "https://www.youtube.com/c/CaminoTV",
    category: "Streetwear & sneakers",
    contentType: "Vidéo",
    desc: "Chaîne YouTube — reviews, unboxings et culture sneaker/streetwear en français.",
    tags: ["YouTube", "Sneakers", "Reviews"],
    social: { youtube: "https://www.youtube.com/c/CaminoTV" },
  },
  {
    id: "a3",
    kind: "account",
    name: "Damien.l",
    url: "https://www.instagram.com/damien.l",
    category: "Style & recommandations",
    contentType: "Créateur",
    desc: "Créateur de contenu — inspirations outfit, marques à découvrir et regard personnel sur la mode.",
    tags: ["Créateur", "Outfits", "Découverte"],
    social: { instagram: "https://www.instagram.com/damien.l" },
  },
  {
    id: "a4",
    kind: "account",
    name: "Highsnobiety",
    url: "https://www.highsnobiety.com",
    category: "Culture & tendances",
    contentType: "Média",
    desc: "Référence globale — tendances, drops et culture streetwear/mainstream.",
    tags: ["Média", "Tendances", "Drops"],
    social: {
      instagram: "https://www.instagram.com/highsnobiety",
      youtube: "https://www.youtube.com/c/Highsnobiety",
    },
  },
];
